### ISSUE TITLE
update README for revised docker compose instructions to reflect new docker container location

### ISSUE THREAD

**Issue by snicker** [snicker/juicepassproxy#11]
per #10 - v0.1.0 published
https://github.com/snicker/juicepassproxy/releases/tag/v0.1.0

@Snuffy2 
> I can then test to ensure it works and will then make another PR to update the Readme with revised Docker Compose instructions.

all yours!

**Comment by snicker** [comment]
@Snuffy2  - this is failing, likely because I do not have a token defined in the secrets of the repository

> Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/snicker/juicepassproxy:0.1.0: unexpected status from POST request to https://ghcr.io/v2/snicker/juicepassproxy/blobs/uploads/: 403 Forbidden

I tried setting up a fine grained access token for deployments, but I must be doing something wrong since GH will not allow me to include a personal access token in the repo secrets.

If you can give me some instructions on setting this part up I can implement this weekend.

**Comment by Snuffy2** [comment]
Hopefully, we can fix it easily with the Repo permissions.

Go into the Repo, Settings, Actions, General.

Change the settings per below:
<img width="1428" alt="2023-11-11_13-52-11" src="https://github.com/snicker/juicepassproxy/assets/6526076/17998284-6cf9-43a6-a29d-fed116e5ac84">

Then try to rerun the Action.

Go into the Repo, Actions, Click the v0.1.0 run. Then click Re-run jobs and cross your fingers.

<img width="1401" alt="2023-11-11_13-55-45" src="https://github.com/snicker/juicepassproxy/assets/6526076/e0cb0282-9b70-40c3-ac56-9ce8861ac47a">

**Comment by snicker** [comment]
Excellent- all working now! https://github.com/snicker/juicepassproxy/pkgs/container/juicepassproxy
