### ISSUE TITLE
Transition from deprecated python telnetlib

### ISSUE THREAD

**Issue by Snuffy2** [snicker/juicepassproxy#25]
Python telnetlib is deprecated in 3.11+ and removed from Python in 3.13. Will need to transition to another package for telnet at some point (not urgent). For now, the Dockerfile is fixed to Python 3.12.

Options could be:
* telnetlib3
* Exscript

**Comment by snicker** [comment]
based on cursory investigation, Exscript seems to be the easiest refactor target
