### ISSUE TITLE
Multiple Juiceboxes

### ISSUE THREAD

**Issue by jeffml42** [snicker/juicepassproxy#44]
Possible to support multiple juiceboxes?

Was able to work around the single juicebox limit by adding a secondary IP on the docker host and running a second instance with JPP_HOST set to the secondary IP.  Also need to set DEVICE_NAME to not conflict in MQTT (e.g. JuiceBox2)

Supporting multiple juiceboxes in a single docker might be too much work.  But if we were able to assign a different port via something like an IP:Port pair in JPP_HOST or maybe a UDPC_PORT variable, that would eliminate the need for the secondary IP.

Either way I'm still very happy with all the work everyone did on this!  Thank you.

**Comment by chevycc** [comment]
Can we use a different UDP port?

**Comment by jeffml42** [comment]
I was able to designate an alternate local container port by using the under documented SRC variable.

Currently SRC set to 0.0.0.0:8048 works as the best workaround until either an additional variable is added (something like DEFAULT_LOCAL_PORT) or SRC is parsed to allow just the port (:8048).  Currently an undefined SRC variable will set it to the local IP but only if no port is defined.  You can also set SRC explicitly to your current IP plus port but that has failed for me when the container IP changes.  0.0.0.0 seems to work instead.

**Comment by Snuffy2** [comment]
You can now specify different ports in v0.3.0 so you should now be able to run multiple versions of the container.
