### ISSUE TITLE
Report "unreachable" when the device is not reachable via the network

### ISSUE THREAD

**Issue by chrisjrn** [snicker/juicepassproxy#47]
Hi!

My JuiceBox lives on a shared clothes dryer circuit with a splitter that turns off the JuiceBox whenever the clothes dryer is operating. When my dryer is on, `juicepassproxy` is showing errors that the JuiceBox is unreachable (no route to host); but Home Assistant has received no updates that it's unreachable.

Would it be possible to send an "unreachable" status to the juicebox whenever the device is unreachable?

--Chris

**Comment by carrel-gr** [comment]
My JuiceBox has poor WiFi signal and loses connection quite often.  I found that juicepassproxy would not recover when that happened.  It appeared to still be providing (stale) mqtt updates to HA.  But even when the JuiceBox reconnected to WiFi, juicepassproxy would not get fresh data.  I have to shutdown the juicepassproxy container and restart it.  It would be great to have juicepassproxy report "unreachable" when the JuiceBox goes offline and it would also be nice to have it re-establish the connection when WiFi comes back.
