### ISSUE TITLE
recommend pinning ha-mqtt-discoverable to 0.13.1 to avoid issues with pydantic-core > 2 not supported easily on 32 bit devices

### ISSUE THREAD

**Issue by snicker** [snicker/juicepassproxy#74]
https://github.com/unixorn/ha-mqtt-discoverable/pull/191#issuecomment-2153543655

see above for details - but I have been unable to get 0.3.0 running on my rpi zero due to a change to ha-mqtt-discoverable (which we haven't pinned to a specific version) moving to `pydantic-core` >2. the opinions on the breaking changes from `pydantic-core` version 1 to version 2 are numerous on the web. In V2 they moved to external dependencies (built in Rust) to improve performance, which has added substantial additional dependencies to use the library, adding complexity where none may be needed.

proposal here is to pin `ha-mqtt-discoverable` to 0.13.1 which will remove the pydantic-core > 2 dependencies and allow me to use this again : )

**Comment by Snuffy2** [comment]
Makes sense for now.
