### ISSUE TITLE
juicebox_commands: Don't "save" the UDPC, causes EEPROM wear and has no effect

### ISSUE THREAD

**Issue by FalconFour** [snicker/juicepassproxy#96]
Using @ivanfmartinez latest version:
Another (very) simple issue: don't issue "save" when changing UDPC. It isn't a config parameter, so it doesn't persist reboots. The `save` command causes ZentriOS to write config variables to EEPROM, all of which are unchanged. We're just changing stream handles during runtime :)

`juicebox_udpcupdater.py` line 159:
```
            if update_required:
                for id in udpc_streams_to_close:
                    _LOGGER.debug(f"Closing UDPC stream: {id}")
                    await self._telnet.close_udpc_stream(id)
                await self._telnet.write_udpc_stream(self._jpp_host, self._udpc_port)
                await self._telnet.save_udpc()
                _LOGGER.info("UDPC IP Saved")
```
Omit `await self._telnet.save_udpc()` and change ` _LOGGER.info("UDPC IP Saved")` to ` _LOGGER.info("UDPC IP Changed")`.

May still be worth preserving the "save_udpc()" function in `juicebox_telnet.py` for future use, e.g. future detection of non-ZAP devices that need a one-time update of `udp.client.remote_host`.

**Comment by ivanfmartinez** [comment]
That part is not related to the juicebox_commands branch changes that I made. 

But I commented it now there https://github.com/snicker/juicepassproxy/pull/69/commits/dd335daf98b88ca440db2bf71c0482b16870c165
